// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPT6rrGCa_5wzXNZY6qCss3e6fBWu5ZUA',
    appId: '1:735261767599:web:809057d587764a554c615a',
    messagingSenderId: '735261767599',
    projectId: 'atutinvestment',
    authDomain: 'atutinvestment.firebaseapp.com',
    storageBucket: 'atutinvestment.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmtWKUp4ke52JKDNfKbcaTtYahvXmnEvE',
    appId: '1:735261767599:android:09340be7e5de18a84c615a',
    messagingSenderId: '735261767599',
    projectId: 'atutinvestment',
    storageBucket: 'atutinvestment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCb6o11JHxdZNLuR7fn4tOThWQqHNfM0Rs',
    appId: '1:735261767599:ios:73ba2445019d547e4c615a',
    messagingSenderId: '735261767599',
    projectId: 'atutinvestment',
    storageBucket: 'atutinvestment.appspot.com',
    iosClientId: '735261767599-bnkqk6b826fpmb50hfm8ohocpv60rdvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.atutinvestmentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCb6o11JHxdZNLuR7fn4tOThWQqHNfM0Rs',
    appId: '1:735261767599:ios:73ba2445019d547e4c615a',
    messagingSenderId: '735261767599',
    projectId: 'atutinvestment',
    storageBucket: 'atutinvestment.appspot.com',
    iosClientId: '735261767599-bnkqk6b826fpmb50hfm8ohocpv60rdvh.apps.googleusercontent.com',
    iosBundleId: 'com.example.atutinvestmentapp',
  );
}
